name: Docker CI
on: [pull_request, push]

jobs:
  run-tests:
      runs-on: ubuntu-latest
      container: dolfinx/dolfinx:v0.8.0
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
      
        - name: Install local package and dependencies
          run: |
            pip install .[test]

        - name: Run tests
          run: |
            python3 -m pytest test/ --cov festim --cov-report xml --cov-report term

        - name: Upload to codecov
          uses: codecov/codecov-action@v4
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: ./coverage.xml